# Generated by Django 4.0.1 on 2022-02-19 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('desc', models.TextField(max_length=1000, verbose_name='Текст під заголовком')),
                ('img', models.ImageField(upload_to='about_us/img', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Про нас',
                'verbose_name_plural': 'Про нас',
            },
        ),
        migrations.CreateModel(
            name='ShopWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='shop_window/img', verbose_name='Картинка')),
                ('sofa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.sofamodel', verbose_name='Диван до якого відноситься картинка')),
            ],
            options={
                'verbose_name': 'Вітрини',
                'verbose_name_plural': 'Вітрини',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок до картинки')),
                ('context', models.TextField(blank=True, max_length=500, verbose_name='Текст до картинки')),
                ('img', models.ImageField(upload_to='section/img', verbose_name='Фотографія')),
                ('sofa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.sofamodel', verbose_name='Диван до якого відноситься картинка')),
            ],
            options={
                'verbose_name': 'Головну картинку',
                'verbose_name_plural': 'Головні картинки',
            },
        ),
    ]
