# Generated by Django 4.0.1 on 2022-02-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
