# Generated by Django 4.0.1 on 2022-02-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_herosection_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='priority',
            field=models.PositiveIntegerField(default=1, verbose_name='Пріоритет показу'),
        ),
    ]
