# Generated by Django 4.0.1 on 2022-02-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Адреса')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='OurShops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Назва міста')),
                ('info', models.TextField(max_length=1000, verbose_name='Інформація про постачальників')),
            ],
            options={
                'verbose_name': 'Наші магазини',
                'verbose_name_plural': 'Наші магазини',
            },
        ),
    ]
