# Generated by Django 4.0.1 on 2022-02-19 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleOurShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Наш магазин',
                'verbose_name_plural': 'Наші магазини',
            },
        ),
        migrations.AddField(
            model_name='ourshops',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contact.titleourshop'),
            preserve_default=False,
        ),
    ]
