# Generated by Django 4.0.1 on 2022-02-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_titleourshop_ourshops_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titleourshop',
            name='desc',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
