# Generated by Django 4.0.1 on 2022-02-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_titleourshop_options_remove_ourshops_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(max_length=200, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.TextField(max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.TextField(max_length=100, verbose_name='Телефон'),
        ),
    ]
