# Generated by Django 4.0.1 on 2022-02-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contact_address_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address_english',
            field=models.TextField(blank=True, default='.', max_length=200, verbose_name='Адреса(english)'),
        ),
        migrations.AddField(
            model_name='ourshops',
            name='city_english',
            field=models.CharField(blank=True, default='.', max_length=100, verbose_name='Назва міста англійською'),
        ),
        migrations.AddField(
            model_name='ourshops',
            name='info_english',
            field=models.TextField(blank=True, default='.', max_length=1000, verbose_name='Інформація про мазагини англійською'),
        ),
        migrations.AddField(
            model_name='titleourshop',
            name='desc_english',
            field=models.TextField(blank=True, default='.', max_length=500),
        ),
        migrations.AddField(
            model_name='titleourshop',
            name='title_english',
            field=models.CharField(blank=True, default='.', max_length=200),
        ),
        migrations.AlterField(
            model_name='ourshops',
            name='info',
            field=models.TextField(max_length=1000, verbose_name='Інформація про мазагини'),
        ),
    ]
