# Generated by Django 4.0.1 on 2022-02-23 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_page', '0003_alter_herosection_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSectionEn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок до картинки англійською')),
                ('context', models.TextField(blank=True, max_length=500, verbose_name='Текст до картинки англійською')),
                ('priority', models.PositiveIntegerField(default=1, verbose_name='Пріоритет показу')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.herosection', verbose_name='Секція до якої відноситься англійський варіант')),
            ],
            options={
                'verbose_name': 'Головну картинку(english)',
                'verbose_name_plural': 'Головні картинки(english)',
            },
        ),
        migrations.CreateModel(
            name='AboutUsEn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок англійською')),
                ('desc', models.TextField(max_length=1000, verbose_name='Текст під заголовком англійською')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.aboutus', verbose_name='Обьект до якого відноситься англійський варіант')),
            ],
        ),
    ]
