# Generated by Django 4.0.1 on 2022-02-15 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SofaColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SofaModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('img', models.ImageField(upload_to='cart/img/model_img')),
            ],
            options={
                'verbose_name': 'Модели диванов',
                'verbose_name_plural': 'Модели диванов',
            },
        ),
        migrations.CreateModel(
            name='SofaTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SofaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=1000)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='cart/img/main_img')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.sofamodels')),
                ('sofa_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.sofacolor')),
                ('sofa_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.sofatypes')),
            ],
            options={
                'verbose_name': 'Диваны',
                'verbose_name_plural': 'Диваны',
            },
        ),
        migrations.CreateModel(
            name='CartImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='cart/img')),
                ('sofa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.sofamodel')),
            ],
        ),
        migrations.CreateModel(
            name='Cart3dModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbx_file', models.FileField(db_index=True, upload_to='cart/3d')),
                ('sofa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.sofamodel')),
            ],
        ),
    ]
