# Generated by Django 4.0.1 on 2022-02-19 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SofaModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Назва моделі')),
                ('img', models.ImageField(upload_to='cart/img/model_img', verbose_name='Картинка моделі')),
            ],
            options={
                'verbose_name': 'Моделі диванів',
                'verbose_name_plural': 'Моделі диванів',
            },
        ),
        migrations.CreateModel(
            name='SofaTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Назва типу')),
            ],
            options={
                'verbose_name': 'Типи виробів',
                'verbose_name_plural': 'Типи виробів',
            },
        ),
        migrations.CreateModel(
            name='SofaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва дивану')),
                ('desc', models.TextField(max_length=1000, verbose_name='Короткий опис товару')),
                ('detail', models.TextField(max_length=2000, verbose_name='Детальний опис')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='cart/img/main_img', verbose_name='Головна картинка')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.sofamodels', verbose_name='Категорія')),
                ('sofa_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.sofatypes', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Дивани',
                'verbose_name_plural': 'Дивани',
            },
        ),
        migrations.CreateModel(
            name='CartImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='cart/img', verbose_name='Додаткові фотографіі')),
                ('sofa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.sofamodel')),
            ],
        ),
        migrations.CreateModel(
            name='Cart3dModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbx_file', models.FileField(db_index=True, upload_to='cart/3d', verbose_name='Файл 3Д моделі')),
                ('sofa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.sofamodel')),
            ],
        ),
    ]
