# Generated by Django 4.0.1 on 2022-02-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sofamodel',
            name='new',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
        migrations.AddField(
            model_name='sofamodel',
            name='priority',
            field=models.PositiveIntegerField(default=1, verbose_name='Приоритет показу диванів в каталозі'),
        ),
    ]
