# Generated by Django 4.0.1 on 2022-02-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_sofamodel_new_sofamodel_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginatorLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=9)),
            ],
        ),
    ]
