# Generated by Django 4.0.1 on 2022-02-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_sofamodel_show_in_main_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sofamodel',
            name='show_in_main_page',
            field=models.BooleanField(default=True, verbose_name='Показувати на головній сторінці'),
        ),
    ]
