# Generated by Django 4.0.1 on 2022-02-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_sofamodel_show_in_main_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sofamodel',
            name='characteristic_english',
            field=models.TextField(blank=True, default='.', max_length=2000, verbose_name='Характеристики товару англійською'),
        ),
        migrations.AddField(
            model_name='sofamodel',
            name='desc_english',
            field=models.TextField(blank=True, default='.', max_length=1000, verbose_name='Короткий опис товару англійською'),
        ),
        migrations.AddField(
            model_name='sofamodel',
            name='detail_english',
            field=models.TextField(blank=True, default='.', max_length=2000, verbose_name='Детальний опис англійською'),
        ),
        migrations.AddField(
            model_name='sofatypes',
            name='name_english',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Назва типу англійською'),
        ),
    ]
