# Generated by Django 4.0.1 on 2022-03-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_sofamodel_characteristic_english_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sofamodel',
            name='title_english',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва дивану англійською(Якщо в цьому є потреба)'),
        ),
    ]
