# Generated by Django 4.0.1 on 2022-02-21 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopWindowUpperSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='shopwindow/img_upper_slider', verbose_name='Фотографія')),
                ('sofa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.sofamodel', verbose_name='Диван до якого відноситься фотографія')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='ShopWindowLowerSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='shopwindow/img_upper_slider', verbose_name='Фотографія')),
                ('sofa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.sofamodel', verbose_name='Диван до якого відноситься фотографія')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='ShopWindowImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='shopwindow/img', verbose_name='Фотографія')),
                ('sofa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.sofamodel', verbose_name='Диван до якого відноситься фотографія')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='MainImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='shopwindow/main_img', verbose_name='Фотографія')),
                ('sofa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.sofamodel', verbose_name='Диван до якого відноситься фотографія')),
            ],
            options={
                'verbose_name': 'Головну фотографію для вітрини',
                'verbose_name_plural': 'Головні фотографії вітрин',
            },
        ),
        migrations.CreateModel(
            name='ImgUnderMainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='shopwindow/img_under_main_img', verbose_name='Фотографія')),
                ('sofa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.sofamodel', verbose_name='Диван до якого відноситься фотографія')),
            ],
            options={
                'verbose_name': 'Фотографію під головними фотографіями',
                'verbose_name_plural': 'Фотографії під головними фотографіями',
            },
        ),
    ]
