# Generated by Django 4.0.1 on 2022-02-21 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopwindow', '0002_alter_imgundermainimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopwindowimages',
            options={'verbose_name': 'Фотографію', 'verbose_name_plural': 'Центральні фотографії'},
        ),
    ]
