# Generated by Django 4.0.1 on 2022-02-22 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_paginatorlimit'),
        ('shopwindow', '0003_alter_shopwindowimages_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgUnderLowerSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='shopwindow/img_under_lower_slider', verbose_name='Фотографія')),
                ('sofa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.sofamodel', verbose_name='Диван до якого відноситься фотографія')),
            ],
            options={
                'verbose_name': 'Фотографію',
                'verbose_name_plural': 'Фотографії під нижнім слайдером',
            },
        ),
    ]
